default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 20
  port: 5433
  username: myapp
  password: password1

development:
  <<: *default
  database: remote_flow

test:
  <<: *default
  database: remote_flow_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: remote_flow
  # username: remote_flow
  # password: <%= ENV['REMOTE_FLOW_DATABASE_PASSWORD'] %>
