development:
  GOOGLE_CLIENT_ID: '677154065603-cqsjsrdlunh4ihqfv7llfddq5qeuo3sc.apps.googleusercontent.com'
  GOOGLE_SECRET_KEY: 'PGYszeRugd4WPYerzh3IRnVO'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_CLIENT_ID: '677154065603-cqsjsrdlunh4ihqfv7llfddq5qeuo3sc.apps.googleusercontent.com'
  GOOGLE_SECRET_KEY: 'PGYszeRugd4WPYerzh3IRnVO'