development:
  GOOGLE_CLIENT_ID: '677154065603-8b612ihbgeaffj70mm7kgco7kpb84h0s.apps.googleusercontent.com'
  GOOGLE_SECRET_KEY: 'Yld4IM3AasaeIgsr3PvcyW7S'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_SECRET_KEY: <%= ENV["GOOGLE_SECRET_KEY"] %>
