development:
  GOOGLE_CLIENT_ID: '677154065603-cqsjsrdlunh4ihqfv7llfddq5qeuo3sc.apps.googleusercontent.com'
  GOOGLE_SECRET_KEY: 'PGYszeRugd4WPYerzh3IRnVO'

  telegram:
    bot:
      token: '807549419:AAESUShzu-CPIc9zu5s_KEPAQdVl0jr74wA'
      username: 'remote_flow_bot'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_CLIENT_ID: '677154065603-cqsjsrdlunh4ihqfv7llfddq5qeuo3sc.apps.googleusercontent.com'
  GOOGLE_SECRET_KEY: 'PGYszeRugd4WPYerzh3IRnVO'
