development:
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_SECRET_KEY: <%= ENV["GOOGLE_SECRET_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_SECRET_KEY: <%= ENV["GOOGLE_SECRET_KEY"] %>
