defaults: &defaults
  token: 'https://hooks.slack.com/services/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'
  channel: '#reflow'
  username: 'notifier-bot'


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
